# @package _group_
_target_: pytorch_lightning.callbacks.ModelCheckpoint
monitor: valid_mrr
mode: max  # this means that model_selection_metric should be maximized
save_last: true
verbose: true
filename: checkpoint_best
save_top_k: 3
