defaults:
  - config
  - override trainer: slurm_aws

task:
  shared_model: false
  in_batch_eval: false
  optim:
    lr: 2e-5
  warmup_steps: 1237

datamodule:
  train_path: /fsx/mhli/wiki/trivia/trivia_train.filtered.jsonl
  val_path: /fsx/mhli/wiki/trivia/trivia_dev.filtered.jsonl
  test_path: /fsx/mhli/wiki/trivia/trivia_dev.filtered.jsonl
  batch_size: 16
  num_negative: 1
  num_val_negative: 1
  num_test_negative: 50
  drop_last: false
  use_title: true

trainer:
  gpus: 8
  num_nodes: 1
  max_epochs: 40
  num_sanity_val_steps: 0
  log_every_n_steps: 10
  gradient_clip_val: 2.0
  precision: 16
  strategy: ddp
